//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSystem.Models.DataB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoansSystemDBEntities : DbContext
    {
        public LoansSystemDBEntities()
            : base("name=LoansSystemDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<LonsRequest> LonsRequests { get; set; }
        public virtual DbSet<RequestStatus> ReqStatus { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<PersonalInformation> PersonalInformations { get; set; }
    }
}
