//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanSystem.Models.DataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LonsRequest
    {
        public int LR_ID { get; set; }
        public System.DateTime LR_Date { get; set; }
        public int CustomerID { get; set; }
        public int BankID { get; set; }
        public string Employer { get; set; }
        public int LenthOfService { get; set; }
        public decimal LoanAmount { get; set; }
        public int InstalmentsPeriod { get; set; }
        public decimal FixedSalary { get; set; }
        public decimal VariableBonus { get; set; }
        public int LoanRequestStatus { get; set; }
        public Nullable<bool> HasCreditCard { get; set; }
        public Nullable<decimal> CreditCardLimit { get; set; }
        public Nullable<bool> HasOverdraft { get; set; }
        public Nullable<decimal> OverdraftAmount { get; set; }
        public Nullable<bool> HasOtherMonthlyPayments { get; set; }
        public Nullable<decimal> OtherMonthlyPaymentAmount { get; set; }
        public int ByAgent { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual RequestStatus RequestStatu { get; set; }
        public virtual Agent Agent { get; set; }
    }
}
