//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_item_units
    {
        public string itemean { get; set; }
        public short unit { get; set; }
        public short codingmethod { get; set; }
        public string originalcode { get; set; }
        public string barcode { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public short buyunit { get; set; }
        public short usage { get; set; }
        public short sellunit { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<short> transid { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public Nullable<short> barcode_print { get; set; }
        public Nullable<short> country { get; set; }
        public string flavour { get; set; }
        public Nullable<short> peices { get; set; }
        public Nullable<decimal> costprice { get; set; }
        public Nullable<decimal> retailprice { get; set; }
        public Nullable<decimal> old_costprice { get; set; }
        public Nullable<decimal> old_retailprice { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<short> velocity_code { get; set; }
        public Nullable<decimal> peicesno { get; set; }
        public Nullable<decimal> discountvalue { get; set; }
        public Nullable<decimal> suggested_price { get; set; }
        public Nullable<short> policyid { get; set; }
        public Nullable<decimal> wholeprice { get; set; }
        public Nullable<System.DateTime> last_modified_time { get; set; }
    
        public virtual sys_item sys_item { get; set; }
    }
}
