//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeIssueApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HQ_sys_item
    {
        public string itemean { get; set; }
        public short itemclass { get; set; }
        public short section { get; set; }
        public short itemgroup { get; set; }
        public short department { get; set; }
        public string a_name { get; set; }
        public string l_name { get; set; }
        public string shortname { get; set; }
        public string flavor { get; set; }
        public Nullable<short> brand { get; set; }
        public Nullable<int> producerno { get; set; }
        public Nullable<short> category { get; set; }
        public string referenceno { get; set; }
        public Nullable<short> color { get; set; }
        public Nullable<decimal> size { get; set; }
        public Nullable<short> measure { get; set; }
        public Nullable<short> hyper_market { get; set; }
        public Nullable<short> class_a { get; set; }
        public Nullable<short> home_delivery { get; set; }
        public Nullable<short> storeinterval { get; set; }
        public Nullable<short> shelfinterval { get; set; }
        public Nullable<short> goodstype { get; set; }
        public Nullable<short> itemtype { get; set; }
        public Nullable<decimal> profit { get; set; }
        public Nullable<decimal> loss_rate { get; set; }
        public Nullable<short> expirycheck { get; set; }
        public Nullable<short> class_c { get; set; }
        public Nullable<short> range_cal { get; set; }
        public Nullable<short> ordered_from { get; set; }
        public Nullable<short> zone { get; set; }
        public string bin_location { get; set; }
        public Nullable<short> class_b { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<System.DateTime> statusdate { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<short> transid { get; set; }
        public Nullable<short> pluupd { get; set; }
        public Nullable<System.DateTime> transdate { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public Nullable<short> whole_sale { get; set; }
        public Nullable<short> nationalty { get; set; }
        public Nullable<short> big_supermarket { get; set; }
        public Nullable<short> module_group { get; set; }
        public Nullable<short> module_no { get; set; }
        public Nullable<short> basic_item { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<short> active { get; set; }
        public Nullable<short> price_class { get; set; }
        public Nullable<short> transtype { get; set; }
        public string item_image { get; set; }
        public Nullable<short> sales_tax { get; set; }
        public Nullable<short> add_tax { get; set; }
    }
}
